//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeedSearcherGui.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeedSearcherGui.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1IV. OK! ähnelt.
        /// </summary>
        internal static string _1ivok {
            get {
                return ResourceManager.GetString("1ivok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ability ähnelt.
        /// </summary>
        internal static string Ability {
            get {
                return ResourceManager.GetString("Ability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Normal ähnelt.
        /// </summary>
        internal static string AbilityNormal {
            get {
                return ResourceManager.GetString("AbilityNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Accelerator ähnelt.
        /// </summary>
        internal static string Accelerator {
            get {
                return ResourceManager.GetString("Accelerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ATK ähnelt.
        /// </summary>
        internal static string ATK {
            get {
                return ResourceManager.GetString("ATK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Axew&apos;s Eye 1 ähnelt.
        /// </summary>
        internal static string Axew1 {
            get {
                return ResourceManager.GetString("Axew1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bridge Field 1 ähnelt.
        /// </summary>
        internal static string Bridge1 {
            get {
                return ResourceManager.GetString("Bridge1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bridge Field 2 ähnelt.
        /// </summary>
        internal static string Bridge2 {
            get {
                return ResourceManager.GetString("Bridge2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bridge Field 3 ähnelt.
        /// </summary>
        internal static string Bridge3 {
            get {
                return ResourceManager.GetString("Bridge3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bridge Field 4 ähnelt.
        /// </summary>
        internal static string Bridge4 {
            get {
                return ResourceManager.GetString("Bridge4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bridge Field 5 ähnelt.
        /// </summary>
        internal static string Bridge5 {
            get {
                return ResourceManager.GetString("Bridge5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bridge Field 6 ähnelt.
        /// </summary>
        internal static string Bridge6 {
            get {
                return ResourceManager.GetString("Bridge6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bridge Field 7 ähnelt.
        /// </summary>
        internal static string Bridge7 {
            get {
                return ResourceManager.GetString("Bridge7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bridge Field 8 ähnelt.
        /// </summary>
        internal static string Bridge8 {
            get {
                return ResourceManager.GetString("Bridge8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bridge Field 9 ähnelt.
        /// </summary>
        internal static string Bridge9 {
            get {
                return ResourceManager.GetString("Bridge9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start Search ähnelt.
        /// </summary>
        internal static string BTStartSearch {
            get {
                return ResourceManager.GetString("BTStartSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Characteristic ähnelt.
        /// </summary>
        internal static string Characteristic {
            get {
                return ResourceManager.GetString("Characteristic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check Ivs ähnelt.
        /// </summary>
        internal static string CheckIVs {
            get {
                return ResourceManager.GetString("CheckIVs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm Ivs ähnelt.
        /// </summary>
        internal static string ConfirmIVs {
            get {
                return ResourceManager.GetString("ConfirmIVs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dappled Grove 1 ähnelt.
        /// </summary>
        internal static string Dappled1 {
            get {
                return ResourceManager.GetString("Dappled1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dappled Grove 2 ähnelt.
        /// </summary>
        internal static string Dappled2 {
            get {
                return ResourceManager.GetString("Dappled2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dappled Grove 3 ähnelt.
        /// </summary>
        internal static string Dappled3 {
            get {
                return ResourceManager.GetString("Dappled3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dappled Grove 4 ähnelt.
        /// </summary>
        internal static string Dappled4 {
            get {
                return ResourceManager.GetString("Dappled4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dappled Grove 5 ähnelt.
        /// </summary>
        internal static string Dappled5 {
            get {
                return ResourceManager.GetString("Dappled5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Day ähnelt.
        /// </summary>
        internal static string Day4 {
            get {
                return ResourceManager.GetString("Day4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1-3IV ähnelt.
        /// </summary>
        internal static string Day4Base {
            get {
                return ResourceManager.GetString("Day4Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}IV {1}/6 ähnelt.
        /// </summary>
        internal static string Day4Follow {
            get {
                return ResourceManager.GetString("Day4Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Day ähnelt.
        /// </summary>
        internal static string Day5 {
            get {
                return ResourceManager.GetString("Day5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Day ähnelt.
        /// </summary>
        internal static string Day6 {
            get {
                return ResourceManager.GetString("Day6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DEF ähnelt.
        /// </summary>
        internal static string DEF {
            get {
                return ResourceManager.GetString("DEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Den ähnelt.
        /// </summary>
        internal static string Den {
            get {
                return ResourceManager.GetString("Den", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fields of Honor 1 ähnelt.
        /// </summary>
        internal static string DLC_17_1 {
            get {
                return ResourceManager.GetString("DLC_17_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fields of Honor 10 ähnelt.
        /// </summary>
        internal static string DLC_17_10 {
            get {
                return ResourceManager.GetString("DLC_17_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fields of Honor 2 ähnelt.
        /// </summary>
        internal static string DLC_17_2 {
            get {
                return ResourceManager.GetString("DLC_17_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fields of Honor 3 ähnelt.
        /// </summary>
        internal static string DLC_17_3 {
            get {
                return ResourceManager.GetString("DLC_17_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fields of Honor 4 ähnelt.
        /// </summary>
        internal static string DLC_17_4 {
            get {
                return ResourceManager.GetString("DLC_17_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fields of Honor 5 ähnelt.
        /// </summary>
        internal static string DLC_17_5 {
            get {
                return ResourceManager.GetString("DLC_17_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fields of Honor 6 ähnelt.
        /// </summary>
        internal static string DLC_17_6 {
            get {
                return ResourceManager.GetString("DLC_17_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fields of Honor 7 ähnelt.
        /// </summary>
        internal static string DLC_17_7 {
            get {
                return ResourceManager.GetString("DLC_17_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fields of Honor 8 ähnelt.
        /// </summary>
        internal static string DLC_17_8 {
            get {
                return ResourceManager.GetString("DLC_17_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fields of Honor 9 ähnelt.
        /// </summary>
        internal static string DLC_17_9 {
            get {
                return ResourceManager.GetString("DLC_17_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soothing Wetlands 1 ähnelt.
        /// </summary>
        internal static string DLC_18_1 {
            get {
                return ResourceManager.GetString("DLC_18_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soothing Wetlands 2 ähnelt.
        /// </summary>
        internal static string DLC_18_2 {
            get {
                return ResourceManager.GetString("DLC_18_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soothing Wetlands 3 ähnelt.
        /// </summary>
        internal static string DLC_18_3 {
            get {
                return ResourceManager.GetString("DLC_18_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soothing Wetlands 4 ähnelt.
        /// </summary>
        internal static string DLC_18_4 {
            get {
                return ResourceManager.GetString("DLC_18_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soothing Wetlands 5 ähnelt.
        /// </summary>
        internal static string DLC_18_5 {
            get {
                return ResourceManager.GetString("DLC_18_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soothing Wetlands 6 ähnelt.
        /// </summary>
        internal static string DLC_18_6 {
            get {
                return ResourceManager.GetString("DLC_18_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soothing Wetlands 7 ähnelt.
        /// </summary>
        internal static string DLC_18_7 {
            get {
                return ResourceManager.GetString("DLC_18_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soothing Wetlands 8 ähnelt.
        /// </summary>
        internal static string DLC_18_8 {
            get {
                return ResourceManager.GetString("DLC_18_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soothing Wetlands 9 ähnelt.
        /// </summary>
        internal static string DLC_18_9 {
            get {
                return ResourceManager.GetString("DLC_18_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forest of Focus 1 ähnelt.
        /// </summary>
        internal static string DLC_19_1 {
            get {
                return ResourceManager.GetString("DLC_19_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forest of Focus 2 ähnelt.
        /// </summary>
        internal static string DLC_19_2 {
            get {
                return ResourceManager.GetString("DLC_19_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forest of Focus 3 ähnelt.
        /// </summary>
        internal static string DLC_19_3 {
            get {
                return ResourceManager.GetString("DLC_19_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forest of Focus 4 ähnelt.
        /// </summary>
        internal static string DLC_19_4 {
            get {
                return ResourceManager.GetString("DLC_19_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forest of Focus 5 ähnelt.
        /// </summary>
        internal static string DLC_19_5 {
            get {
                return ResourceManager.GetString("DLC_19_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forest of Focus 6 ähnelt.
        /// </summary>
        internal static string DLC_19_6 {
            get {
                return ResourceManager.GetString("DLC_19_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Challenge Beach 1 ähnelt.
        /// </summary>
        internal static string DLC_20_1 {
            get {
                return ResourceManager.GetString("DLC_20_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Challenge Beach 2 ähnelt.
        /// </summary>
        internal static string DLC_20_2 {
            get {
                return ResourceManager.GetString("DLC_20_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Challenge Beach 3 ähnelt.
        /// </summary>
        internal static string DLC_20_3 {
            get {
                return ResourceManager.GetString("DLC_20_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Challenge Beach 4 ähnelt.
        /// </summary>
        internal static string DLC_20_4 {
            get {
                return ResourceManager.GetString("DLC_20_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Challenge Beach 5 ähnelt.
        /// </summary>
        internal static string DLC_20_5 {
            get {
                return ResourceManager.GetString("DLC_20_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Challenge Beach 6 ähnelt.
        /// </summary>
        internal static string DLC_20_6 {
            get {
                return ResourceManager.GetString("DLC_20_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Challenge Beach 7 ähnelt.
        /// </summary>
        internal static string DLC_20_7 {
            get {
                return ResourceManager.GetString("DLC_20_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Challenge Beach 8 ähnelt.
        /// </summary>
        internal static string DLC_20_8 {
            get {
                return ResourceManager.GetString("DLC_20_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Brawlers&apos; Cave 1 ähnelt.
        /// </summary>
        internal static string DLC_21_1 {
            get {
                return ResourceManager.GetString("DLC_21_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Challenge Road 1 ähnelt.
        /// </summary>
        internal static string DLC_22_1 {
            get {
                return ResourceManager.GetString("DLC_22_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Challenge Road 2 ähnelt.
        /// </summary>
        internal static string DLC_22_2 {
            get {
                return ResourceManager.GetString("DLC_22_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Challenge Road 3 ähnelt.
        /// </summary>
        internal static string DLC_22_3 {
            get {
                return ResourceManager.GetString("DLC_22_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Challenge Road 4 ähnelt.
        /// </summary>
        internal static string DLC_22_4 {
            get {
                return ResourceManager.GetString("DLC_22_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Courageous Cavern 1 ähnelt.
        /// </summary>
        internal static string DLC_23_1 {
            get {
                return ResourceManager.GetString("DLC_23_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Courageous Cavern 2 ähnelt.
        /// </summary>
        internal static string DLC_23_2 {
            get {
                return ResourceManager.GetString("DLC_23_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Courageous Cavern 3 ähnelt.
        /// </summary>
        internal static string DLC_23_3 {
            get {
                return ResourceManager.GetString("DLC_23_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Courageous Cavern 4 ähnelt.
        /// </summary>
        internal static string DLC_23_4 {
            get {
                return ResourceManager.GetString("DLC_23_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Courageous Cavern 5 ähnelt.
        /// </summary>
        internal static string DLC_23_5 {
            get {
                return ResourceManager.GetString("DLC_23_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Courageous Cavern 6 ähnelt.
        /// </summary>
        internal static string DLC_23_6 {
            get {
                return ResourceManager.GetString("DLC_23_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loop Lagoon 1 ähnelt.
        /// </summary>
        internal static string DLC_24_1 {
            get {
                return ResourceManager.GetString("DLC_24_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loop Lagoon 2 ähnelt.
        /// </summary>
        internal static string DLC_24_2 {
            get {
                return ResourceManager.GetString("DLC_24_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loop Lagoon 3 ähnelt.
        /// </summary>
        internal static string DLC_24_3 {
            get {
                return ResourceManager.GetString("DLC_24_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loop Lagoon 4 ähnelt.
        /// </summary>
        internal static string DLC_24_4 {
            get {
                return ResourceManager.GetString("DLC_24_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Training Lowlands 1 ähnelt.
        /// </summary>
        internal static string DLC_25_1 {
            get {
                return ResourceManager.GetString("DLC_25_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Training Lowlands 2 ähnelt.
        /// </summary>
        internal static string DLC_25_2 {
            get {
                return ResourceManager.GetString("DLC_25_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Training Lowlands 3 ähnelt.
        /// </summary>
        internal static string DLC_25_3 {
            get {
                return ResourceManager.GetString("DLC_25_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Training Lowlands 4 ähnelt.
        /// </summary>
        internal static string DLC_25_4 {
            get {
                return ResourceManager.GetString("DLC_25_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Training Lowlands 5 ähnelt.
        /// </summary>
        internal static string DLC_25_5 {
            get {
                return ResourceManager.GetString("DLC_25_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Training Lowlands 6 ähnelt.
        /// </summary>
        internal static string DLC_25_6 {
            get {
                return ResourceManager.GetString("DLC_25_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Training Lowlands 7 ähnelt.
        /// </summary>
        internal static string DLC_25_7 {
            get {
                return ResourceManager.GetString("DLC_25_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Potbottom Desert 1 ähnelt.
        /// </summary>
        internal static string DLC_26_1 {
            get {
                return ResourceManager.GetString("DLC_26_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Potbottom Desert 2 ähnelt.
        /// </summary>
        internal static string DLC_26_2 {
            get {
                return ResourceManager.GetString("DLC_26_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Potbottom Desert 3 ähnelt.
        /// </summary>
        internal static string DLC_26_3 {
            get {
                return ResourceManager.GetString("DLC_26_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Workout Sea 1 ähnelt.
        /// </summary>
        internal static string DLC_27_1 {
            get {
                return ResourceManager.GetString("DLC_27_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Workout Sea 2 ähnelt.
        /// </summary>
        internal static string DLC_27_2 {
            get {
                return ResourceManager.GetString("DLC_27_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Workout Sea 3 ähnelt.
        /// </summary>
        internal static string DLC_27_3 {
            get {
                return ResourceManager.GetString("DLC_27_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Workout Sea 4 ähnelt.
        /// </summary>
        internal static string DLC_27_4 {
            get {
                return ResourceManager.GetString("DLC_27_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Workout Sea 5 ähnelt.
        /// </summary>
        internal static string DLC_27_5 {
            get {
                return ResourceManager.GetString("DLC_27_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Workout Sea 6 ähnelt.
        /// </summary>
        internal static string DLC_27_6 {
            get {
                return ResourceManager.GetString("DLC_27_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Workout Sea 7 ähnelt.
        /// </summary>
        internal static string DLC_27_7 {
            get {
                return ResourceManager.GetString("DLC_27_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stepping-Stone Sea 1 ähnelt.
        /// </summary>
        internal static string DLC_28_1 {
            get {
                return ResourceManager.GetString("DLC_28_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stepping-Stone Sea 2 ähnelt.
        /// </summary>
        internal static string DLC_28_2 {
            get {
                return ResourceManager.GetString("DLC_28_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stepping-Stone Sea 3 ähnelt.
        /// </summary>
        internal static string DLC_28_3 {
            get {
                return ResourceManager.GetString("DLC_28_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stepping-Stone Sea 4 ähnelt.
        /// </summary>
        internal static string DLC_28_4 {
            get {
                return ResourceManager.GetString("DLC_28_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stepping-Stone Sea 5 ähnelt.
        /// </summary>
        internal static string DLC_28_5 {
            get {
                return ResourceManager.GetString("DLC_28_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stepping-Stone Sea 6 ähnelt.
        /// </summary>
        internal static string DLC_28_6 {
            get {
                return ResourceManager.GetString("DLC_28_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stepping-Stone Sea 7 ähnelt.
        /// </summary>
        internal static string DLC_28_7 {
            get {
                return ResourceManager.GetString("DLC_28_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stepping-Stone Sea 8 ähnelt.
        /// </summary>
        internal static string DLC_28_8 {
            get {
                return ResourceManager.GetString("DLC_28_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stepping-Stone Sea 9 ähnelt.
        /// </summary>
        internal static string DLC_28_9 {
            get {
                return ResourceManager.GetString("DLC_28_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insular Sea 1 ähnelt.
        /// </summary>
        internal static string DLC_29_1 {
            get {
                return ResourceManager.GetString("DLC_29_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insular Sea 2 ähnelt.
        /// </summary>
        internal static string DLC_29_2 {
            get {
                return ResourceManager.GetString("DLC_29_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insular Sea 3 ähnelt.
        /// </summary>
        internal static string DLC_29_3 {
            get {
                return ResourceManager.GetString("DLC_29_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insular Sea 4 ähnelt.
        /// </summary>
        internal static string DLC_29_4 {
            get {
                return ResourceManager.GetString("DLC_29_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insular Sea 5 ähnelt.
        /// </summary>
        internal static string DLC_29_5 {
            get {
                return ResourceManager.GetString("DLC_29_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Honeycalm Sea 1 ähnelt.
        /// </summary>
        internal static string DLC_30_1 {
            get {
                return ResourceManager.GetString("DLC_30_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Honeycalm Sea 2 ähnelt.
        /// </summary>
        internal static string DLC_30_2 {
            get {
                return ResourceManager.GetString("DLC_30_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Honeycalm Sea 3 ähnelt.
        /// </summary>
        internal static string DLC_30_3 {
            get {
                return ResourceManager.GetString("DLC_30_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Honeycalm Sea 4 ähnelt.
        /// </summary>
        internal static string DLC_30_4 {
            get {
                return ResourceManager.GetString("DLC_30_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Honeycalm Sea 5 ähnelt.
        /// </summary>
        internal static string DLC_30_5 {
            get {
                return ResourceManager.GetString("DLC_30_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Honeycalm Island 1 ähnelt.
        /// </summary>
        internal static string DLC_31_1 {
            get {
                return ResourceManager.GetString("DLC_31_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Honeycalm Island 2 ähnelt.
        /// </summary>
        internal static string DLC_31_2 {
            get {
                return ResourceManager.GetString("DLC_31_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Honeycalm Island 3 ähnelt.
        /// </summary>
        internal static string DLC_31_3 {
            get {
                return ResourceManager.GetString("DLC_31_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Honeycalm Island 4 ähnelt.
        /// </summary>
        internal static string DLC_31_4 {
            get {
                return ResourceManager.GetString("DLC_31_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Honeycalm Island 5 ähnelt.
        /// </summary>
        internal static string DLC_31_5 {
            get {
                return ResourceManager.GetString("DLC_31_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Honeycalm Island 6 ähnelt.
        /// </summary>
        internal static string DLC_31_6 {
            get {
                return ResourceManager.GetString("DLC_31_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Slippery Slope 1 ähnelt.
        /// </summary>
        internal static string DLC_32_1 {
            get {
                return ResourceManager.GetString("DLC_32_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Slippery Slope 2 ähnelt.
        /// </summary>
        internal static string DLC_32_2 {
            get {
                return ResourceManager.GetString("DLC_32_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Slippery Slope 3 ähnelt.
        /// </summary>
        internal static string DLC_32_3 {
            get {
                return ResourceManager.GetString("DLC_32_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Slippery Slope 4 ähnelt.
        /// </summary>
        internal static string DLC_32_4 {
            get {
                return ResourceManager.GetString("DLC_32_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Slippery Slope 5 ähnelt.
        /// </summary>
        internal static string DLC_32_5 {
            get {
                return ResourceManager.GetString("DLC_32_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Slippery Slope 6 ähnelt.
        /// </summary>
        internal static string DLC_32_6 {
            get {
                return ResourceManager.GetString("DLC_32_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frostpoint Field 1 ähnelt.
        /// </summary>
        internal static string DLC_33_1 {
            get {
                return ResourceManager.GetString("DLC_33_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frostpoint Field 2 ähnelt.
        /// </summary>
        internal static string DLC_33_2 {
            get {
                return ResourceManager.GetString("DLC_33_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frostpoint Field 3 ähnelt.
        /// </summary>
        internal static string DLC_33_3 {
            get {
                return ResourceManager.GetString("DLC_33_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frostpoint Field 4 ähnelt.
        /// </summary>
        internal static string DLC_33_4 {
            get {
                return ResourceManager.GetString("DLC_33_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frostpoint Field 5 ähnelt.
        /// </summary>
        internal static string DLC_33_5 {
            get {
                return ResourceManager.GetString("DLC_33_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant’s Bed 1 ähnelt.
        /// </summary>
        internal static string DLC_34_1 {
            get {
                return ResourceManager.GetString("DLC_34_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant’s Bed 10 ähnelt.
        /// </summary>
        internal static string DLC_34_10 {
            get {
                return ResourceManager.GetString("DLC_34_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant’s Bed 11 ähnelt.
        /// </summary>
        internal static string DLC_34_11 {
            get {
                return ResourceManager.GetString("DLC_34_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant’s Bed 12 ähnelt.
        /// </summary>
        internal static string DLC_34_12 {
            get {
                return ResourceManager.GetString("DLC_34_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant’s Bed 13 ähnelt.
        /// </summary>
        internal static string DLC_34_13 {
            get {
                return ResourceManager.GetString("DLC_34_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant’s Bed 14 ähnelt.
        /// </summary>
        internal static string DLC_34_14 {
            get {
                return ResourceManager.GetString("DLC_34_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant’s Bed 15 ähnelt.
        /// </summary>
        internal static string DLC_34_15 {
            get {
                return ResourceManager.GetString("DLC_34_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant’s Bed 16 ähnelt.
        /// </summary>
        internal static string DLC_34_16 {
            get {
                return ResourceManager.GetString("DLC_34_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant’s Bed 17 ähnelt.
        /// </summary>
        internal static string DLC_34_17 {
            get {
                return ResourceManager.GetString("DLC_34_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant’s Bed 18 ähnelt.
        /// </summary>
        internal static string DLC_34_18 {
            get {
                return ResourceManager.GetString("DLC_34_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant’s Bed 19 ähnelt.
        /// </summary>
        internal static string DLC_34_19 {
            get {
                return ResourceManager.GetString("DLC_34_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant’s Bed 2 ähnelt.
        /// </summary>
        internal static string DLC_34_2 {
            get {
                return ResourceManager.GetString("DLC_34_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant’s Bed 20 ähnelt.
        /// </summary>
        internal static string DLC_34_20 {
            get {
                return ResourceManager.GetString("DLC_34_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant’s Bed 21 ähnelt.
        /// </summary>
        internal static string DLC_34_21 {
            get {
                return ResourceManager.GetString("DLC_34_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant’s Bed 3 ähnelt.
        /// </summary>
        internal static string DLC_34_3 {
            get {
                return ResourceManager.GetString("DLC_34_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant’s Bed 4 ähnelt.
        /// </summary>
        internal static string DLC_34_4 {
            get {
                return ResourceManager.GetString("DLC_34_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant’s Bed 5 ähnelt.
        /// </summary>
        internal static string DLC_34_5 {
            get {
                return ResourceManager.GetString("DLC_34_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant’s Bed 6 ähnelt.
        /// </summary>
        internal static string DLC_34_6 {
            get {
                return ResourceManager.GetString("DLC_34_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant’s Bed 7 ähnelt.
        /// </summary>
        internal static string DLC_34_7 {
            get {
                return ResourceManager.GetString("DLC_34_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant’s Bed 8 ähnelt.
        /// </summary>
        internal static string DLC_34_8 {
            get {
                return ResourceManager.GetString("DLC_34_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant’s Bed 9 ähnelt.
        /// </summary>
        internal static string DLC_34_9 {
            get {
                return ResourceManager.GetString("DLC_34_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Old Cemetery 1 ähnelt.
        /// </summary>
        internal static string DLC_35_1 {
            get {
                return ResourceManager.GetString("DLC_35_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Old Cemetery 2 ähnelt.
        /// </summary>
        internal static string DLC_35_2 {
            get {
                return ResourceManager.GetString("DLC_35_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Snowslide Slope 1 ähnelt.
        /// </summary>
        internal static string DLC_36_1 {
            get {
                return ResourceManager.GetString("DLC_36_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Snowslide Slope 2 ähnelt.
        /// </summary>
        internal static string DLC_36_2 {
            get {
                return ResourceManager.GetString("DLC_36_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Snowslide Slope 3 ähnelt.
        /// </summary>
        internal static string DLC_36_3 {
            get {
                return ResourceManager.GetString("DLC_36_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Snowslide Slope 4 ähnelt.
        /// </summary>
        internal static string DLC_36_4 {
            get {
                return ResourceManager.GetString("DLC_36_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Snowslide Slope 5 ähnelt.
        /// </summary>
        internal static string DLC_36_5 {
            get {
                return ResourceManager.GetString("DLC_36_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Snowslide Slope 6 ähnelt.
        /// </summary>
        internal static string DLC_36_6 {
            get {
                return ResourceManager.GetString("DLC_36_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Snowslide Slope 7 ähnelt.
        /// </summary>
        internal static string DLC_36_7 {
            get {
                return ResourceManager.GetString("DLC_36_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Snowslide Slope 8 ähnelt.
        /// </summary>
        internal static string DLC_36_8 {
            get {
                return ResourceManager.GetString("DLC_36_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Snowslide Slope 9 ähnelt.
        /// </summary>
        internal static string DLC_36_9 {
            get {
                return ResourceManager.GetString("DLC_36_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Path to the Peak 1 ähnelt.
        /// </summary>
        internal static string DLC_37_1 {
            get {
                return ResourceManager.GetString("DLC_37_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Path to the Peak 2 ähnelt.
        /// </summary>
        internal static string DLC_37_2 {
            get {
                return ResourceManager.GetString("DLC_37_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Path to the Peak 3 ähnelt.
        /// </summary>
        internal static string DLC_37_3 {
            get {
                return ResourceManager.GetString("DLC_37_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crown Shrine 1 ähnelt.
        /// </summary>
        internal static string DLC_38_1 {
            get {
                return ResourceManager.GetString("DLC_38_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant’s Foot 1 ähnelt.
        /// </summary>
        internal static string DLC_39_1 {
            get {
                return ResourceManager.GetString("DLC_39_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant’s Foot 2 ähnelt.
        /// </summary>
        internal static string DLC_39_2 {
            get {
                return ResourceManager.GetString("DLC_39_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant’s Foot 3 ähnelt.
        /// </summary>
        internal static string DLC_39_3 {
            get {
                return ResourceManager.GetString("DLC_39_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant’s Foot 4 ähnelt.
        /// </summary>
        internal static string DLC_39_4 {
            get {
                return ResourceManager.GetString("DLC_39_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant’s Foot 5 ähnelt.
        /// </summary>
        internal static string DLC_39_5 {
            get {
                return ResourceManager.GetString("DLC_39_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frigid Sea 1 ähnelt.
        /// </summary>
        internal static string DLC_40_1 {
            get {
                return ResourceManager.GetString("DLC_40_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frigid Sea 10 ähnelt.
        /// </summary>
        internal static string DLC_40_10 {
            get {
                return ResourceManager.GetString("DLC_40_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frigid Sea 11 ähnelt.
        /// </summary>
        internal static string DLC_40_11 {
            get {
                return ResourceManager.GetString("DLC_40_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frigid Sea 12 ähnelt.
        /// </summary>
        internal static string DLC_40_12 {
            get {
                return ResourceManager.GetString("DLC_40_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frigid Sea 13 ähnelt.
        /// </summary>
        internal static string DLC_40_13 {
            get {
                return ResourceManager.GetString("DLC_40_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frigid Sea 14 ähnelt.
        /// </summary>
        internal static string DLC_40_14 {
            get {
                return ResourceManager.GetString("DLC_40_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frigid Sea 2 ähnelt.
        /// </summary>
        internal static string DLC_40_2 {
            get {
                return ResourceManager.GetString("DLC_40_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frigid Sea 3 ähnelt.
        /// </summary>
        internal static string DLC_40_3 {
            get {
                return ResourceManager.GetString("DLC_40_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frigid Sea 4 ähnelt.
        /// </summary>
        internal static string DLC_40_4 {
            get {
                return ResourceManager.GetString("DLC_40_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frigid Sea 5 ähnelt.
        /// </summary>
        internal static string DLC_40_5 {
            get {
                return ResourceManager.GetString("DLC_40_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frigid Sea 6 ähnelt.
        /// </summary>
        internal static string DLC_40_6 {
            get {
                return ResourceManager.GetString("DLC_40_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frigid Sea 7 ähnelt.
        /// </summary>
        internal static string DLC_40_7 {
            get {
                return ResourceManager.GetString("DLC_40_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frigid Sea 8 ähnelt.
        /// </summary>
        internal static string DLC_40_8 {
            get {
                return ResourceManager.GetString("DLC_40_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frigid Sea 9 ähnelt.
        /// </summary>
        internal static string DLC_40_9 {
            get {
                return ResourceManager.GetString("DLC_40_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Three-Point Pass 1 ähnelt.
        /// </summary>
        internal static string DLC_41_1 {
            get {
                return ResourceManager.GetString("DLC_41_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Three-Point Pass 2 ähnelt.
        /// </summary>
        internal static string DLC_41_2 {
            get {
                return ResourceManager.GetString("DLC_41_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ballimere Lake 1 ähnelt.
        /// </summary>
        internal static string DLC_42_1 {
            get {
                return ResourceManager.GetString("DLC_42_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ballimere Lake 10 ähnelt.
        /// </summary>
        internal static string DLC_42_10 {
            get {
                return ResourceManager.GetString("DLC_42_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ballimere Lake 11 ähnelt.
        /// </summary>
        internal static string DLC_42_11 {
            get {
                return ResourceManager.GetString("DLC_42_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ballimere Lake 12 ähnelt.
        /// </summary>
        internal static string DLC_42_12 {
            get {
                return ResourceManager.GetString("DLC_42_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ballimere Lake 13 ähnelt.
        /// </summary>
        internal static string DLC_42_13 {
            get {
                return ResourceManager.GetString("DLC_42_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ballimere Lake 14 ähnelt.
        /// </summary>
        internal static string DLC_42_14 {
            get {
                return ResourceManager.GetString("DLC_42_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ballimere Lake 15 ähnelt.
        /// </summary>
        internal static string DLC_42_15 {
            get {
                return ResourceManager.GetString("DLC_42_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ballimere Lake 16 ähnelt.
        /// </summary>
        internal static string DLC_42_16 {
            get {
                return ResourceManager.GetString("DLC_42_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ballimere Lake 17 ähnelt.
        /// </summary>
        internal static string DLC_42_17 {
            get {
                return ResourceManager.GetString("DLC_42_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ballimere Lake 2 ähnelt.
        /// </summary>
        internal static string DLC_42_2 {
            get {
                return ResourceManager.GetString("DLC_42_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ballimere Lake 3 ähnelt.
        /// </summary>
        internal static string DLC_42_3 {
            get {
                return ResourceManager.GetString("DLC_42_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ballimere Lake 4 ähnelt.
        /// </summary>
        internal static string DLC_42_4 {
            get {
                return ResourceManager.GetString("DLC_42_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ballimere Lake 5 ähnelt.
        /// </summary>
        internal static string DLC_42_5 {
            get {
                return ResourceManager.GetString("DLC_42_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ballimere Lake 6 ähnelt.
        /// </summary>
        internal static string DLC_42_6 {
            get {
                return ResourceManager.GetString("DLC_42_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ballimere Lake 7 ähnelt.
        /// </summary>
        internal static string DLC_42_7 {
            get {
                return ResourceManager.GetString("DLC_42_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ballimere Lake 8 ähnelt.
        /// </summary>
        internal static string DLC_42_8 {
            get {
                return ResourceManager.GetString("DLC_42_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ballimere Lake 9 ähnelt.
        /// </summary>
        internal static string DLC_42_9 {
            get {
                return ResourceManager.GetString("DLC_42_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dyna Tree Hill 1 ähnelt.
        /// </summary>
        internal static string DLC_43_1 {
            get {
                return ResourceManager.GetString("DLC_43_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dusty Bowl 1 ähnelt.
        /// </summary>
        internal static string Dusty1 {
            get {
                return ResourceManager.GetString("Dusty1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dusty Bowl 2 ähnelt.
        /// </summary>
        internal static string Dusty2 {
            get {
                return ResourceManager.GetString("Dusty2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dusty Bowl 3 ähnelt.
        /// </summary>
        internal static string Dusty3 {
            get {
                return ResourceManager.GetString("Dusty3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dusty Bowl 4 ähnelt.
        /// </summary>
        internal static string Dusty4 {
            get {
                return ResourceManager.GetString("Dusty4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dusty Bowl 5 ähnelt.
        /// </summary>
        internal static string Dusty5 {
            get {
                return ResourceManager.GetString("Dusty5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dusty Bowl 6 ähnelt.
        /// </summary>
        internal static string Dusty6 {
            get {
                return ResourceManager.GetString("Dusty6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dusty Bowl 7 ähnelt.
        /// </summary>
        internal static string Dusty7 {
            get {
                return ResourceManager.GetString("Dusty7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dusty Bowl 8 ähnelt.
        /// </summary>
        internal static string Dusty8 {
            get {
                return ResourceManager.GetString("Dusty8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dusty Bowl 9 ähnelt.
        /// </summary>
        internal static string Dusty9 {
            get {
                return ResourceManager.GetString("Dusty9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die East Lake Axewell 1 ähnelt.
        /// </summary>
        internal static string East1 {
            get {
                return ResourceManager.GetString("East1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die East Lake Axewell 2 ähnelt.
        /// </summary>
        internal static string East2 {
            get {
                return ResourceManager.GetString("East2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die East Lake Axewell 3 ähnelt.
        /// </summary>
        internal static string East3 {
            get {
                return ResourceManager.GetString("East3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die East Lake Axewell 4 ähnelt.
        /// </summary>
        internal static string East4 {
            get {
                return ResourceManager.GetString("East4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die East Lake Axewell 5 ähnelt.
        /// </summary>
        internal static string East5 {
            get {
                return ResourceManager.GetString("East5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Event Den ähnelt.
        /// </summary>
        internal static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export ähnelt.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export/Import ähnelt.
        /// </summary>
        internal static string ExportImport {
            get {
                return ResourceManager.GetString("ExportImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Game ähnelt.
        /// </summary>
        internal static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant&apos;s Seat 1 ähnelt.
        /// </summary>
        internal static string Giant1 {
            get {
                return ResourceManager.GetString("Giant1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant&apos;s Mirror 1 ähnelt.
        /// </summary>
        internal static string Giant11 {
            get {
                return ResourceManager.GetString("Giant11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant&apos;s Cap 1 ähnelt.
        /// </summary>
        internal static string Giant12 {
            get {
                return ResourceManager.GetString("Giant12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant&apos;s Seat 2 ähnelt.
        /// </summary>
        internal static string Giant2 {
            get {
                return ResourceManager.GetString("Giant2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant&apos;s Mirror 2 ähnelt.
        /// </summary>
        internal static string Giant21 {
            get {
                return ResourceManager.GetString("Giant21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant&apos;s Cap 2 ähnelt.
        /// </summary>
        internal static string Giant22 {
            get {
                return ResourceManager.GetString("Giant22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant&apos;s Seat 3 ähnelt.
        /// </summary>
        internal static string Giant3 {
            get {
                return ResourceManager.GetString("Giant3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant&apos;s Mirror 3 ähnelt.
        /// </summary>
        internal static string Giant31 {
            get {
                return ResourceManager.GetString("Giant31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant&apos;s Cap 3 ähnelt.
        /// </summary>
        internal static string Giant32 {
            get {
                return ResourceManager.GetString("Giant32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant&apos;s Seat 4 ähnelt.
        /// </summary>
        internal static string Giant4 {
            get {
                return ResourceManager.GetString("Giant4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant&apos;s Mirror 4 ähnelt.
        /// </summary>
        internal static string Giant41 {
            get {
                return ResourceManager.GetString("Giant41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant&apos;s Cap 4 ähnelt.
        /// </summary>
        internal static string Giant42 {
            get {
                return ResourceManager.GetString("Giant42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant&apos;s Seat 5 ähnelt.
        /// </summary>
        internal static string Giant5 {
            get {
                return ResourceManager.GetString("Giant5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant&apos;s Mirror 5 ähnelt.
        /// </summary>
        internal static string Giant51 {
            get {
                return ResourceManager.GetString("Giant51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant&apos;s Cap 5 ähnelt.
        /// </summary>
        internal static string Giant52 {
            get {
                return ResourceManager.GetString("Giant52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hammerlocke Hills 1 ähnelt.
        /// </summary>
        internal static string Hammerlocke1 {
            get {
                return ResourceManager.GetString("Hammerlocke1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hammerlocke Hills 2 ähnelt.
        /// </summary>
        internal static string Hammerlocke2 {
            get {
                return ResourceManager.GetString("Hammerlocke2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hammerlocke Hills 3 ähnelt.
        /// </summary>
        internal static string Hammerlocke3 {
            get {
                return ResourceManager.GetString("Hammerlocke3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hammerlocke Hills 4 ähnelt.
        /// </summary>
        internal static string Hammerlocke4 {
            get {
                return ResourceManager.GetString("Hammerlocke4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hammerlocke Hills 5 ähnelt.
        /// </summary>
        internal static string Hammerlocke5 {
            get {
                return ResourceManager.GetString("Hammerlocke5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hammerlocke Hills 6 ähnelt.
        /// </summary>
        internal static string Hammerlocke6 {
            get {
                return ResourceManager.GetString("Hammerlocke6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hammerlocke Hills 7 ähnelt.
        /// </summary>
        internal static string Hammerlocke7 {
            get {
                return ResourceManager.GetString("Hammerlocke7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HP ähnelt.
        /// </summary>
        internal static string HP {
            get {
                return ResourceManager.GetString("HP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import ähnelt.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculation Range ähnelt.
        /// </summary>
        internal static string IVDeviation {
            get {
                return ResourceManager.GetString("IVDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lake of Outrage 1 ähnelt.
        /// </summary>
        internal static string Lake1 {
            get {
                return ResourceManager.GetString("Lake1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lake of Outrage 2 ähnelt.
        /// </summary>
        internal static string Lake2 {
            get {
                return ResourceManager.GetString("Lake2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lake of Outrage 3 ähnelt.
        /// </summary>
        internal static string Lake3 {
            get {
                return ResourceManager.GetString("Lake3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lake of Outrage 4 ähnelt.
        /// </summary>
        internal static string Lake4 {
            get {
                return ResourceManager.GetString("Lake4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Languages ähnelt.
        /// </summary>
        internal static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Level ähnelt.
        /// </summary>
        internal static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Motostoke Riverbank 1 ähnelt.
        /// </summary>
        internal static string Motostoke1 {
            get {
                return ResourceManager.GetString("Motostoke1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Motostoke Riverbank 2 ähnelt.
        /// </summary>
        internal static string Motostoke2 {
            get {
                return ResourceManager.GetString("Motostoke2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Motostoke Riverbank 3 ähnelt.
        /// </summary>
        internal static string Motostoke3 {
            get {
                return ResourceManager.GetString("Motostoke3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Motostoke Riverbank 4 ähnelt.
        /// </summary>
        internal static string Motostoke4 {
            get {
                return ResourceManager.GetString("Motostoke4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nature ähnelt.
        /// </summary>
        internal static string Nature {
            get {
                return ResourceManager.GetString("Nature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nest ähnelt.
        /// </summary>
        internal static string Nest {
            get {
                return ResourceManager.GetString("Nest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Search ähnelt.
        /// </summary>
        internal static string NewSearch {
            get {
                return ResourceManager.GetString("NewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NOK! No follow up possible. ähnelt.
        /// </summary>
        internal static string NOK {
            get {
                return ResourceManager.GetString("NOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Normal ähnelt.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die North Lake Miloch 1 ähnelt.
        /// </summary>
        internal static string North1 {
            get {
                return ResourceManager.GetString("North1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die North Lake Miloch 2 ähnelt.
        /// </summary>
        internal static string North2 {
            get {
                return ResourceManager.GetString("North2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die North Lake Miloch 3 ähnelt.
        /// </summary>
        internal static string North3 {
            get {
                return ResourceManager.GetString("North3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die North Lake Miloch 4 ähnelt.
        /// </summary>
        internal static string North4 {
            get {
                return ResourceManager.GetString("North4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die North Lake Miloch 5 ähnelt.
        /// </summary>
        internal static string North5 {
            get {
                return ResourceManager.GetString("North5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die North Lake Miloch 6 ähnelt.
        /// </summary>
        internal static string North6 {
            get {
                return ResourceManager.GetString("North6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Seed found. Please increase Calculation Range and run the tool again. ähnelt.
        /// </summary>
        internal static string NoSeed {
            get {
                return ResourceManager.GetString("NoSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not enough 31 IVs set for this Pokémon. ähnelt.
        /// </summary>
        internal static string NotEnough {
            get {
                return ResourceManager.GetString("NotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pokémon ähnelt.
        /// </summary>
        internal static string Pokemon {
            get {
                return ResourceManager.GetString("Pokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rare ähnelt.
        /// </summary>
        internal static string Rare {
            get {
                return ResourceManager.GetString("Rare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rarity ähnelt.
        /// </summary>
        internal static string Rarity {
            get {
                return ResourceManager.GetString("Rarity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reccomended Next Level ähnelt.
        /// </summary>
        internal static string RecommendedNextLevel {
            get {
                return ResourceManager.GetString("RecommendedNextLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rolling Fields 1 ähnelt.
        /// </summary>
        internal static string Rolling1 {
            get {
                return ResourceManager.GetString("Rolling1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rolling Fields 2 ähnelt.
        /// </summary>
        internal static string Rolling2 {
            get {
                return ResourceManager.GetString("Rolling2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rolling Fields 3 ähnelt.
        /// </summary>
        internal static string Rolling3 {
            get {
                return ResourceManager.GetString("Rolling3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rolling Fields 4 ähnelt.
        /// </summary>
        internal static string Rolling4 {
            get {
                return ResourceManager.GetString("Rolling4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rolling Fields 5 ähnelt.
        /// </summary>
        internal static string Rolling5 {
            get {
                return ResourceManager.GetString("Rolling5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rolling Fields 6 ähnelt.
        /// </summary>
        internal static string Rolling6 {
            get {
                return ResourceManager.GetString("Rolling6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rolling Fields 7 ähnelt.
        /// </summary>
        internal static string Rolling7 {
            get {
                return ResourceManager.GetString("Rolling7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rolling Fields 8 ähnelt.
        /// </summary>
        internal static string Rolling8 {
            get {
                return ResourceManager.GetString("Rolling8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rolling Fields 9 ähnelt.
        /// </summary>
        internal static string Rolling9 {
            get {
                return ResourceManager.GetString("Rolling9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Seed Checker ähnelt.
        /// </summary>
        internal static string SeedChecker {
            get {
                return ResourceManager.GetString("SeedChecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set Event ähnelt.
        /// </summary>
        internal static string SetEvent {
            get {
                return ResourceManager.GetString("SetEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shield ähnelt.
        /// </summary>
        internal static string Shield {
            get {
                return ResourceManager.GetString("Shield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die South Lake Miloch 1 ähnelt.
        /// </summary>
        internal static string South1 {
            get {
                return ResourceManager.GetString("South1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die South Lake Miloch 2 ähnelt.
        /// </summary>
        internal static string South2 {
            get {
                return ResourceManager.GetString("South2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die South Lake Miloch 3 ähnelt.
        /// </summary>
        internal static string South3 {
            get {
                return ResourceManager.GetString("South3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die South Lake Miloch 4 ähnelt.
        /// </summary>
        internal static string South4 {
            get {
                return ResourceManager.GetString("South4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die South Lake Miloch 5 ähnelt.
        /// </summary>
        internal static string South5 {
            get {
                return ResourceManager.GetString("South5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SPA ähnelt.
        /// </summary>
        internal static string SPA {
            get {
                return ResourceManager.GetString("SPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SPD ähnelt.
        /// </summary>
        internal static string SPD {
            get {
                return ResourceManager.GetString("SPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SPE ähnelt.
        /// </summary>
        internal static string SPE {
            get {
                return ResourceManager.GetString("SPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search ähnelt.
        /// </summary>
        internal static string StartSearch {
            get {
                return ResourceManager.GetString("StartSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stony Wilderness 10 ähnelt.
        /// </summary>
        internal static string Stony0 {
            get {
                return ResourceManager.GetString("Stony0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stony Wilderness 1 ähnelt.
        /// </summary>
        internal static string Stony1 {
            get {
                return ResourceManager.GetString("Stony1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stony Wilderness 11 ähnelt.
        /// </summary>
        internal static string Stony11 {
            get {
                return ResourceManager.GetString("Stony11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stony Wilderness 2 ähnelt.
        /// </summary>
        internal static string Stony2 {
            get {
                return ResourceManager.GetString("Stony2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stony Wilderness 12 ähnelt.
        /// </summary>
        internal static string Stony21 {
            get {
                return ResourceManager.GetString("Stony21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stony Wilderness 3 ähnelt.
        /// </summary>
        internal static string Stony3 {
            get {
                return ResourceManager.GetString("Stony3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stony Wilderness 4 ähnelt.
        /// </summary>
        internal static string Stony4 {
            get {
                return ResourceManager.GetString("Stony4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stony Wilderness 5 ähnelt.
        /// </summary>
        internal static string Stony5 {
            get {
                return ResourceManager.GetString("Stony5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stony Wilderness 6 ähnelt.
        /// </summary>
        internal static string Stony6 {
            get {
                return ResourceManager.GetString("Stony6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stony Wilderness 7 ähnelt.
        /// </summary>
        internal static string Stony7 {
            get {
                return ResourceManager.GetString("Stony7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stony Wilderness 8 ähnelt.
        /// </summary>
        internal static string Stony8 {
            get {
                return ResourceManager.GetString("Stony8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stony Wilderness 9 ähnelt.
        /// </summary>
        internal static string Stony9 {
            get {
                return ResourceManager.GetString("Stony9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop Search ähnelt.
        /// </summary>
        internal static string StopSearch {
            get {
                return ResourceManager.GetString("StopSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sword ähnelt.
        /// </summary>
        internal static string Sword {
            get {
                return ResourceManager.GetString("Sword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Too many IVs are at 31. Please use a different Pokémon. ähnelt.
        /// </summary>
        internal static string TooMany {
            get {
                return ResourceManager.GetString("TooMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown ähnelt.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update Event Database ähnelt.
        /// </summary>
        internal static string UpdateEvent {
            get {
                return ResourceManager.GetString("UpdateEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Watchtower Ruins 1 ähnelt.
        /// </summary>
        internal static string Watchtower1 {
            get {
                return ResourceManager.GetString("Watchtower1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Watchtower Ruins 2 ähnelt.
        /// </summary>
        internal static string Watchtower2 {
            get {
                return ResourceManager.GetString("Watchtower2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die West Lake Axewell 1 ähnelt.
        /// </summary>
        internal static string West1 {
            get {
                return ResourceManager.GetString("West1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die West Lake Axewell 2 ähnelt.
        /// </summary>
        internal static string West2 {
            get {
                return ResourceManager.GetString("West2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die West Lake Axewell 3 ähnelt.
        /// </summary>
        internal static string West3 {
            get {
                return ResourceManager.GetString("West3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die West Lake Axewell 4 ähnelt.
        /// </summary>
        internal static string West4 {
            get {
                return ResourceManager.GetString("West4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die West Lake Axewell 5 ähnelt.
        /// </summary>
        internal static string West5 {
            get {
                return ResourceManager.GetString("West5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die West Lake Axewell 6 ähnelt.
        /// </summary>
        internal static string West6 {
            get {
                return ResourceManager.GetString("West6", resourceCulture);
            }
        }
    }
}
