//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeedSearcherGui.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeedSearcherGui.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1IV. OK! ähnelt.
        /// </summary>
        internal static string _1ivok {
            get {
                return ResourceManager.GetString("1ivok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ability ähnelt.
        /// </summary>
        internal static string Ability {
            get {
                return ResourceManager.GetString("Ability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Normal ähnelt.
        /// </summary>
        internal static string AbilityNormal {
            get {
                return ResourceManager.GetString("AbilityNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ATK ähnelt.
        /// </summary>
        internal static string ATK {
            get {
                return ResourceManager.GetString("ATK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Axew&apos;s Eye 1 ähnelt.
        /// </summary>
        internal static string Axew1 {
            get {
                return ResourceManager.GetString("Axew1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bridge Field 1 ähnelt.
        /// </summary>
        internal static string Bridge1 {
            get {
                return ResourceManager.GetString("Bridge1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bridge Field 2 ähnelt.
        /// </summary>
        internal static string Bridge2 {
            get {
                return ResourceManager.GetString("Bridge2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bridge Field 3 ähnelt.
        /// </summary>
        internal static string Bridge3 {
            get {
                return ResourceManager.GetString("Bridge3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bridge Field 4 ähnelt.
        /// </summary>
        internal static string Bridge4 {
            get {
                return ResourceManager.GetString("Bridge4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bridge Field 5 ähnelt.
        /// </summary>
        internal static string Bridge5 {
            get {
                return ResourceManager.GetString("Bridge5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bridge Field 6 ähnelt.
        /// </summary>
        internal static string Bridge6 {
            get {
                return ResourceManager.GetString("Bridge6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bridge Field 7 ähnelt.
        /// </summary>
        internal static string Bridge7 {
            get {
                return ResourceManager.GetString("Bridge7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bridge Field 8 ähnelt.
        /// </summary>
        internal static string Bridge8 {
            get {
                return ResourceManager.GetString("Bridge8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bridge Field 9 ähnelt.
        /// </summary>
        internal static string Bridge9 {
            get {
                return ResourceManager.GetString("Bridge9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Characteristic ähnelt.
        /// </summary>
        internal static string Characteristic {
            get {
                return ResourceManager.GetString("Characteristic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dappled Grove 1 ähnelt.
        /// </summary>
        internal static string Dappled1 {
            get {
                return ResourceManager.GetString("Dappled1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dappled Grove 2 ähnelt.
        /// </summary>
        internal static string Dappled2 {
            get {
                return ResourceManager.GetString("Dappled2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dappled Grove 3 ähnelt.
        /// </summary>
        internal static string Dappled3 {
            get {
                return ResourceManager.GetString("Dappled3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dappled Grove 4 ähnelt.
        /// </summary>
        internal static string Dappled4 {
            get {
                return ResourceManager.GetString("Dappled4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dappled Grove 5 ähnelt.
        /// </summary>
        internal static string Dappled5 {
            get {
                return ResourceManager.GetString("Dappled5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pokémon Info Day 4 ähnelt.
        /// </summary>
        internal static string Day4 {
            get {
                return ResourceManager.GetString("Day4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1-3IV ähnelt.
        /// </summary>
        internal static string Day4Base {
            get {
                return ResourceManager.GetString("Day4Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}IV {1}/6 ähnelt.
        /// </summary>
        internal static string Day4Follow {
            get {
                return ResourceManager.GetString("Day4Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pokémon Info Day 5 ähnelt.
        /// </summary>
        internal static string Day5 {
            get {
                return ResourceManager.GetString("Day5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pokémon Info Day 6 ähnelt.
        /// </summary>
        internal static string Day6 {
            get {
                return ResourceManager.GetString("Day6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DEF ähnelt.
        /// </summary>
        internal static string DEF {
            get {
                return ResourceManager.GetString("DEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Den ähnelt.
        /// </summary>
        internal static string Den {
            get {
                return ResourceManager.GetString("Den", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dusty Bowl 1 ähnelt.
        /// </summary>
        internal static string Dusty1 {
            get {
                return ResourceManager.GetString("Dusty1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dusty Bowl 2 ähnelt.
        /// </summary>
        internal static string Dusty2 {
            get {
                return ResourceManager.GetString("Dusty2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dusty Bowl 3 ähnelt.
        /// </summary>
        internal static string Dusty3 {
            get {
                return ResourceManager.GetString("Dusty3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dusty Bowl 4 ähnelt.
        /// </summary>
        internal static string Dusty4 {
            get {
                return ResourceManager.GetString("Dusty4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dusty Bowl 5 ähnelt.
        /// </summary>
        internal static string Dusty5 {
            get {
                return ResourceManager.GetString("Dusty5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dusty Bowl 6 ähnelt.
        /// </summary>
        internal static string Dusty6 {
            get {
                return ResourceManager.GetString("Dusty6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dusty Bowl 7 ähnelt.
        /// </summary>
        internal static string Dusty7 {
            get {
                return ResourceManager.GetString("Dusty7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dusty Bowl 8 ähnelt.
        /// </summary>
        internal static string Dusty8 {
            get {
                return ResourceManager.GetString("Dusty8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dusty Bowl 9 ähnelt.
        /// </summary>
        internal static string Dusty9 {
            get {
                return ResourceManager.GetString("Dusty9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die East Lake Axewell 1 ähnelt.
        /// </summary>
        internal static string East1 {
            get {
                return ResourceManager.GetString("East1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die East Lake Axewell 2 ähnelt.
        /// </summary>
        internal static string East2 {
            get {
                return ResourceManager.GetString("East2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die East Lake Axewell 3 ähnelt.
        /// </summary>
        internal static string East3 {
            get {
                return ResourceManager.GetString("East3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die East Lake Axewell 4 ähnelt.
        /// </summary>
        internal static string East4 {
            get {
                return ResourceManager.GetString("East4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die East Lake Axewell 5 ähnelt.
        /// </summary>
        internal static string East5 {
            get {
                return ResourceManager.GetString("East5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Event Den ähnelt.
        /// </summary>
        internal static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Game ähnelt.
        /// </summary>
        internal static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant&apos;s Seat 1 ähnelt.
        /// </summary>
        internal static string Giant1 {
            get {
                return ResourceManager.GetString("Giant1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant&apos;s Mirror 1 ähnelt.
        /// </summary>
        internal static string Giant11 {
            get {
                return ResourceManager.GetString("Giant11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant&apos;s Cap 1 ähnelt.
        /// </summary>
        internal static string Giant12 {
            get {
                return ResourceManager.GetString("Giant12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant&apos;s Seat 2 ähnelt.
        /// </summary>
        internal static string Giant2 {
            get {
                return ResourceManager.GetString("Giant2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant&apos;s Mirror 2 ähnelt.
        /// </summary>
        internal static string Giant21 {
            get {
                return ResourceManager.GetString("Giant21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant&apos;s Cap 2 ähnelt.
        /// </summary>
        internal static string Giant22 {
            get {
                return ResourceManager.GetString("Giant22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant&apos;s Seat 3 ähnelt.
        /// </summary>
        internal static string Giant3 {
            get {
                return ResourceManager.GetString("Giant3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant&apos;s Mirror 3 ähnelt.
        /// </summary>
        internal static string Giant31 {
            get {
                return ResourceManager.GetString("Giant31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant&apos;s Cap 3 ähnelt.
        /// </summary>
        internal static string Giant32 {
            get {
                return ResourceManager.GetString("Giant32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant&apos;s Seat 4 ähnelt.
        /// </summary>
        internal static string Giant4 {
            get {
                return ResourceManager.GetString("Giant4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant&apos;s Mirror 4 ähnelt.
        /// </summary>
        internal static string Giant41 {
            get {
                return ResourceManager.GetString("Giant41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant&apos;s Cap 4 ähnelt.
        /// </summary>
        internal static string Giant42 {
            get {
                return ResourceManager.GetString("Giant42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant&apos;s Seat 5 ähnelt.
        /// </summary>
        internal static string Giant5 {
            get {
                return ResourceManager.GetString("Giant5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant&apos;s Mirror 5 ähnelt.
        /// </summary>
        internal static string Giant51 {
            get {
                return ResourceManager.GetString("Giant51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Giant&apos;s Cap 5 ähnelt.
        /// </summary>
        internal static string Giant52 {
            get {
                return ResourceManager.GetString("Giant52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hammerlocke Hills 1 ähnelt.
        /// </summary>
        internal static string Hammerlocke1 {
            get {
                return ResourceManager.GetString("Hammerlocke1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hammerlocke Hills 2 ähnelt.
        /// </summary>
        internal static string Hammerlocke2 {
            get {
                return ResourceManager.GetString("Hammerlocke2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hammerlocke Hills 3 ähnelt.
        /// </summary>
        internal static string Hammerlocke3 {
            get {
                return ResourceManager.GetString("Hammerlocke3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hammerlocke Hills 4 ähnelt.
        /// </summary>
        internal static string Hammerlocke4 {
            get {
                return ResourceManager.GetString("Hammerlocke4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hammerlocke Hills 5 ähnelt.
        /// </summary>
        internal static string Hammerlocke5 {
            get {
                return ResourceManager.GetString("Hammerlocke5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hammerlocke Hills 6 ähnelt.
        /// </summary>
        internal static string Hammerlocke6 {
            get {
                return ResourceManager.GetString("Hammerlocke6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hammerlocke Hills 7 ähnelt.
        /// </summary>
        internal static string Hammerlocke7 {
            get {
                return ResourceManager.GetString("Hammerlocke7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HP ähnelt.
        /// </summary>
        internal static string HP {
            get {
                return ResourceManager.GetString("HP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IV Deviation ähnelt.
        /// </summary>
        internal static string IVDeviation {
            get {
                return ResourceManager.GetString("IVDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lake of Outrage 1 ähnelt.
        /// </summary>
        internal static string Lake1 {
            get {
                return ResourceManager.GetString("Lake1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lake of Outrage 2 ähnelt.
        /// </summary>
        internal static string Lake2 {
            get {
                return ResourceManager.GetString("Lake2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lake of Outrage 3 ähnelt.
        /// </summary>
        internal static string Lake3 {
            get {
                return ResourceManager.GetString("Lake3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lake of Outrage 4 ähnelt.
        /// </summary>
        internal static string Lake4 {
            get {
                return ResourceManager.GetString("Lake4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Motostoke Riverbank 1 ähnelt.
        /// </summary>
        internal static string Motostoke1 {
            get {
                return ResourceManager.GetString("Motostoke1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Motostoke Riverbank 2 ähnelt.
        /// </summary>
        internal static string Motostoke2 {
            get {
                return ResourceManager.GetString("Motostoke2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Motostoke Riverbank 3 ähnelt.
        /// </summary>
        internal static string Motostoke3 {
            get {
                return ResourceManager.GetString("Motostoke3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Motostoke Riverbank 4 ähnelt.
        /// </summary>
        internal static string Motostoke4 {
            get {
                return ResourceManager.GetString("Motostoke4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nature ähnelt.
        /// </summary>
        internal static string Nature {
            get {
                return ResourceManager.GetString("Nature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Normal ähnelt.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die North Lake Miloch 1 ähnelt.
        /// </summary>
        internal static string North1 {
            get {
                return ResourceManager.GetString("North1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die North Lake Miloch 2 ähnelt.
        /// </summary>
        internal static string North2 {
            get {
                return ResourceManager.GetString("North2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die North Lake Miloch 3 ähnelt.
        /// </summary>
        internal static string North3 {
            get {
                return ResourceManager.GetString("North3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die North Lake Miloch 4 ähnelt.
        /// </summary>
        internal static string North4 {
            get {
                return ResourceManager.GetString("North4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die North Lake Miloch 5 ähnelt.
        /// </summary>
        internal static string North5 {
            get {
                return ResourceManager.GetString("North5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die North Lake Miloch 6 ähnelt.
        /// </summary>
        internal static string North6 {
            get {
                return ResourceManager.GetString("North6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pokémon ähnelt.
        /// </summary>
        internal static string Pokemon {
            get {
                return ResourceManager.GetString("Pokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rare ähnelt.
        /// </summary>
        internal static string Rare {
            get {
                return ResourceManager.GetString("Rare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rarity ähnelt.
        /// </summary>
        internal static string Rarity {
            get {
                return ResourceManager.GetString("Rarity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rolling Fields 1 ähnelt.
        /// </summary>
        internal static string Rolling1 {
            get {
                return ResourceManager.GetString("Rolling1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rolling Fields 2 ähnelt.
        /// </summary>
        internal static string Rolling2 {
            get {
                return ResourceManager.GetString("Rolling2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rolling Fields 3 ähnelt.
        /// </summary>
        internal static string Rolling3 {
            get {
                return ResourceManager.GetString("Rolling3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rolling Fields 4 ähnelt.
        /// </summary>
        internal static string Rolling4 {
            get {
                return ResourceManager.GetString("Rolling4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rolling Fields 5 ähnelt.
        /// </summary>
        internal static string Rolling5 {
            get {
                return ResourceManager.GetString("Rolling5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rolling Fields 6 ähnelt.
        /// </summary>
        internal static string Rolling6 {
            get {
                return ResourceManager.GetString("Rolling6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rolling Fields 7 ähnelt.
        /// </summary>
        internal static string Rolling7 {
            get {
                return ResourceManager.GetString("Rolling7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rolling Fields 8 ähnelt.
        /// </summary>
        internal static string Rolling8 {
            get {
                return ResourceManager.GetString("Rolling8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rolling Fields 9 ähnelt.
        /// </summary>
        internal static string Rolling9 {
            get {
                return ResourceManager.GetString("Rolling9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shield ähnelt.
        /// </summary>
        internal static string Shield {
            get {
                return ResourceManager.GetString("Shield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die South Lake Miloch 1 ähnelt.
        /// </summary>
        internal static string South1 {
            get {
                return ResourceManager.GetString("South1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die South Lake Miloch 2 ähnelt.
        /// </summary>
        internal static string South2 {
            get {
                return ResourceManager.GetString("South2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die South Lake Miloch 3 ähnelt.
        /// </summary>
        internal static string South3 {
            get {
                return ResourceManager.GetString("South3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die South Lake Miloch 4 ähnelt.
        /// </summary>
        internal static string South4 {
            get {
                return ResourceManager.GetString("South4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die South Lake Miloch 5 ähnelt.
        /// </summary>
        internal static string South5 {
            get {
                return ResourceManager.GetString("South5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SPA ähnelt.
        /// </summary>
        internal static string SPA {
            get {
                return ResourceManager.GetString("SPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SPD ähnelt.
        /// </summary>
        internal static string SPD {
            get {
                return ResourceManager.GetString("SPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SPE ähnelt.
        /// </summary>
        internal static string SPE {
            get {
                return ResourceManager.GetString("SPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stony Wilderness 10 ähnelt.
        /// </summary>
        internal static string Stony0 {
            get {
                return ResourceManager.GetString("Stony0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stony Wilderness 1 ähnelt.
        /// </summary>
        internal static string Stony1 {
            get {
                return ResourceManager.GetString("Stony1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stony Wilderness 11 ähnelt.
        /// </summary>
        internal static string Stony11 {
            get {
                return ResourceManager.GetString("Stony11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stony Wilderness 2 ähnelt.
        /// </summary>
        internal static string Stony2 {
            get {
                return ResourceManager.GetString("Stony2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stony Wilderness 12 ähnelt.
        /// </summary>
        internal static string Stony21 {
            get {
                return ResourceManager.GetString("Stony21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stony Wilderness 3 ähnelt.
        /// </summary>
        internal static string Stony3 {
            get {
                return ResourceManager.GetString("Stony3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stony Wilderness 4 ähnelt.
        /// </summary>
        internal static string Stony4 {
            get {
                return ResourceManager.GetString("Stony4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stony Wilderness 5 ähnelt.
        /// </summary>
        internal static string Stony5 {
            get {
                return ResourceManager.GetString("Stony5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stony Wilderness 6 ähnelt.
        /// </summary>
        internal static string Stony6 {
            get {
                return ResourceManager.GetString("Stony6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stony Wilderness 7 ähnelt.
        /// </summary>
        internal static string Stony7 {
            get {
                return ResourceManager.GetString("Stony7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stony Wilderness 8 ähnelt.
        /// </summary>
        internal static string Stony8 {
            get {
                return ResourceManager.GetString("Stony8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stony Wilderness 9 ähnelt.
        /// </summary>
        internal static string Stony9 {
            get {
                return ResourceManager.GetString("Stony9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sword ähnelt.
        /// </summary>
        internal static string Sword {
            get {
                return ResourceManager.GetString("Sword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown ähnelt.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Watchtower Ruins 1 ähnelt.
        /// </summary>
        internal static string Watchtower1 {
            get {
                return ResourceManager.GetString("Watchtower1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Watchtower Ruins 2 ähnelt.
        /// </summary>
        internal static string Watchtower2 {
            get {
                return ResourceManager.GetString("Watchtower2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die West Lake Axewell 1 ähnelt.
        /// </summary>
        internal static string West1 {
            get {
                return ResourceManager.GetString("West1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die West Lake Axewell 2 ähnelt.
        /// </summary>
        internal static string West2 {
            get {
                return ResourceManager.GetString("West2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die West Lake Axewell 3 ähnelt.
        /// </summary>
        internal static string West3 {
            get {
                return ResourceManager.GetString("West3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die West Lake Axewell 4 ähnelt.
        /// </summary>
        internal static string West4 {
            get {
                return ResourceManager.GetString("West4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die West Lake Axewell 5 ähnelt.
        /// </summary>
        internal static string West5 {
            get {
                return ResourceManager.GetString("West5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die West Lake Axewell 6 ähnelt.
        /// </summary>
        internal static string West6 {
            get {
                return ResourceManager.GetString("West6", resourceCulture);
            }
        }
    }
}
